-- CreateEnum
CREATE TYPE "CampaignProgress" AS ENUM ('GATHER_RATES', 'REVIEW_RATES', 'APPROVED_FOR_CAMPAIGN', 'IN_NEGOTIATION', 'AWAITING_SHIPMENT', 'AWAITING_DELIVERABLES', 'CONTENT_REVIEW', 'AWAITING_PARTNER_POST', 'APPROVED_FOR_PAYMENT', 'COMPLETE', 'NOT_APPROVED', 'ALL_PARTNERS');

-- AlterTable
ALTER TABLE "campaigns" ADD COLUMN     "campaign_progress" "CampaignProgress" NOT NULL DEFAULT 'NOT_APPROVED';
