-- AlterTable
ALTER TABLE "campaigns" ALTER COLUMN "budget" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "total_expense" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "product_expense" SET DATA TYPE DOUBLE PRECISION;
