-- CreateEnum
CREATE TYPE "PaymentStatus" AS ENUM ('PAID', 'DUE');

-- CreateEnum
CREATE TYPE "ProfileStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');

-- CreateTable
CREATE TABLE "partners" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "profile_status" "ProfileStatus" NOT NULL DEFAULT 'ACTIVE',
    "linkedin_connections" INTEGER NOT NULL DEFAULT 0,
    "youtube_following" INTEGER NOT NULL DEFAULT 0,
    "snapchat_following" INTEGER NOT NULL DEFAULT 0,
    "x_following" INTEGER NOT NULL DEFAULT 0,
    "pinterest_following" INTEGER NOT NULL DEFAULT 0,
    "tiktok_following" INTEGER NOT NULL DEFAULT 0,
    "facebook_following" INTEGER NOT NULL DEFAULT 0,
    "instagram_following" INTEGER NOT NULL DEFAULT 0,
    "website" TEXT,
    "medium" TEXT,
    "soundcloud" TEXT,
    "spotify" TEXT,
    "open_to_gifting" BOOLEAN NOT NULL DEFAULT false,
    "state" TEXT,
    "city" TEXT,
    "production_hq" TEXT,
    "representation" TEXT,
    "revo_content_platform" TEXT,
    "live_status" BOOLEAN NOT NULL DEFAULT false,
    "occupation" TEXT,
    "payment_link" TEXT,
    "country" TEXT,
    "client" TEXT,
    "notes" TEXT,
    "facebook" TEXT,
    "instagram" TEXT,
    "linkedin" TEXT,
    "mailing_address" TEXT,
    "phone" TEXT,
    "pinterest" TEXT,
    "profile_image" TEXT,
    "partner_rate" DOUBLE PRECISION,
    "refusal_reason" TEXT,
    "snapchat" TEXT,
    "stakeholder" TEXT,
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "tiktok" TEXT,
    "total_expense" DOUBLE PRECISION,
    "twitch" TEXT,
    "x" TEXT,
    "youtube" TEXT,
    "revo_amazon_order" TEXT,
    "amazon_review_link" TEXT,
    "amazon_review_cupper" TEXT,
    "amazon_review_the_pill" TEXT,
    "amazon_storefront" TEXT,
    "campaign_month" TEXT,
    "revo_ig_post" TEXT,
    "one_off_expense" DOUBLE PRECISION,
    "partner_ig_rate" DOUBLE PRECISION,
    "partner_tt_rate" DOUBLE PRECISION,
    "partner_yt_rate" DOUBLE PRECISION,
    "paid_amount" DOUBLE PRECISION,
    "contributed_engagement" INTEGER NOT NULL DEFAULT 0,
    "audience" INTEGER NOT NULL DEFAULT 0,
    "previous_collab_expense" DOUBLE PRECISION,
    "product_cog_expense" DOUBLE PRECISION,
    "revos_offer" TEXT,
    "remaining_credits" DOUBLE PRECISION,
    "tt_post" TEXT,
    "total_roi" DOUBLE PRECISION,
    "ugc_payment_status" "PaymentStatus" NOT NULL DEFAULT 'DUE',
    "ugc_retainer_amount" DOUBLE PRECISION,
    "ugc_tiktok_link" TEXT,
    "revo_ugc_army_tt_user" TEXT,
    "whatsapp" TEXT,
    "yt_post" TEXT,
    "levanta_page_view" INTEGER NOT NULL DEFAULT 0,
    "levanta_all_add_to_carts" INTEGER NOT NULL DEFAULT 0,
    "levanta_conversations" INTEGER NOT NULL DEFAULT 0,
    "levanta_all_sales" INTEGER NOT NULL DEFAULT 0,
    "levanta_all_commission" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "partner_post_view" INTEGER NOT NULL DEFAULT 0,
    "sourced_from" TEXT,
    "conversions_bundle_cupper" INTEGER NOT NULL DEFAULT 0,
    "conversions_message" INTEGER NOT NULL DEFAULT 0,
    "conversions_cupper" INTEGER NOT NULL DEFAULT 0,
    "conversions_oils" INTEGER NOT NULL DEFAULT 0,
    "conversions_walking_pad" INTEGER NOT NULL DEFAULT 0,
    "estimated_tax" DOUBLE PRECISION,
    "shipping_fba_fee" DOUBLE PRECISION,
    "levanta_affiliate_fee" DOUBLE PRECISION,
    "paypal_fee" DOUBLE PRECISION,
    "shipping_expense" DOUBLE PRECISION,
    "amazon_referral_fee" DOUBLE PRECISION,
    "amazon_order_total" DOUBLE PRECISION,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "partners_pkey" PRIMARY KEY ("id")
);
